---
name: workbench installation
hosts: rstudio-node
become: true
tasks:
  - name: Install gdebi
    apt:
      name: gdebi-core
      state: present
        
  - name: downloading workbench deb file
    get_url:
      url: https://download2.rstudio.org/server/bionic/amd64/rstudio-workbench-2022.12.0-353.pro20-amd64.deb
      dest: /tmp/rstudio-workbench-2022.12.0-353.pro20-amd64.deb
      mode: 0644

  - name: installing workbench deb
    shell: "gdebi rstudio-workbench-2022.12.0-353.pro20-amd64.deb"
    args:
      creates: "/usr/bin/rstudio-workbench"
      


    