---
- name: os pre-requisites
  hosts: rtsudio-node
  become: true
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
# while installing packages, state can be present(package exists) if already installed, Ansible won't take any further action regarding installation., absent(remove if exists), latest (upgrade if exists)    
    - name: install default jdk
      ansible.builtin.apt:
        name: default-jdk
        state: present

    - name: install default jre
      apt:
        name: default-jre
        state: present

    